server:
  port: 8060
  
service:
  endpoint:
    allowed-addresses: >
      127.0.0.1,
      10.0.0.2
    allowed-endpoints: >
      /v3/api-docs,
      /*/swagger*/**,
      /queue/session/v1
  management:
    url: http://127.0.0.1:8090  
  jwt:
    secret: 2BB80D537B1DA3E38BD30361AA855686BDE0EACD7162FEF6A25FE97BF527A25B
    expire: 1

spring:
  kafka:
    consumer:
      bootstrap-servers: 10.0.0.2:9092
      group-id: trackerforce_task_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.trackerforce.queue.model
    producer:
      bootstrap-servers: 10.0.0.2:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer